# Generated by Django 2.2.6 on 2019-10-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loans',
            new_name='Loan',
        ),
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
